### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [adrilu7/cdmx-2018-06-bc-core-am-data-dashboard#3]
Hola @AdrianaTV y @adrilu7 
He estado revisando el proyecto y tengo algunos comentarios:

1. Buen trabajo de ux, se nota la investigación que hicieron para poder cumplir con las exigencias y necesidad del usuario objetivo.

2. Si bien ya pueden imprimir el listado de estudiantes de la cuarta generación de Lima, les recomiendo comenzar a trabajar con la data a profundidad lo antes posible (se encontrarán con toda la lógica para jalar la información y hacer los cálculos) y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto. 

3. Ojo con el nombre de las variables, es algo que está dentro de la ŕubrica de niveles, deben ser lo más descriptivas posibles y ojalá en ingles, lo comento especialmente por la variable `perro` que vi por ahí.

4. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

5. No hay mucho más para dar feedback, recuerden revisar los test, les da pistas de incluso como deben ser las estructuras de las funciones.

6. Ojo con el trabajo colaborativo, solo hay commits de @adrilu7 

Vamos con todoooo! a romperlaaaa :smile: :metal: :muscle: :heart:

**Comment by AdrianaEsvereidyTV** [comment]
Hola Coach Alexandra, 
Te agradecemos todo el feedback que nos ofreces estamos arduamente trabajando para mejorar y espera excelentes progresos en este fin de semana.

Haz sido una gran guía en especial para conectar los repositorios, estamos atentas a tus comentarios.

Saludos,
Esve =D

**Comment by nerdale** [comment]
Daré por cerrado el issue :smile: 
:rocket:
